### ISSUE TITLE
Picture Exif metadata are lost from the original picture after using CameraRoll.save 

### ISSUE THREAD

**Issue by AlaeddineJendoubi** [react-native-cameraroll/react-native-cameraroll#249]
after using RNCamera to take a picture and write metadata, and save it to cache. 
I used CameraRoll to save the picture from the app cache to cameraRoll folder, but the metadata is lost from the picture that's saved in the camera roll

**Comment by baiross** [comment]
weee you able to fix this issue?

**Comment by AlaeddineJendoubi** [comment]
kinda, i saw that it was fixed in a previous PR, so i downgraded to that version 1.4.1 . this is the issue https://github.com/react-native-cameraroll/react-native-cameraroll/issues/125 . the wired part is that the fixes in this Pr already exists in the current version but it doesn’t work. Anyway, downgrading works without breaking anything, at least for me. tell me if you find another way out

**Comment by vmia159** [comment]
I don't know why they somehow revert the change from 1.4.1 but I was using this patch file and works in ios. 
Android have exif data when saving so no need to patch.

```patch
diff --git a/node_modules/@react-native-camera-roll/camera-roll/ios/RNCCameraRollManager.m b/node_modules/@react-native-camera-roll/camera-roll/ios/RNCCameraRollManager.m
index 570a434..4d775a7 100644
--- a/node_modules/@react-native-camera-roll/camera-roll/ios/RNCCameraRollManager.m
+++ b/node_modules/@react-native-camera-roll/camera-roll/ios/RNCCameraRollManager.m
@@ -171,7 +171,7 @@ RCT_EXPORT_METHOD(saveToCameraRoll:(NSURLRequest *)request
       } else {
         NSData *data = [NSData dataWithContentsOfURL:inputURI];
         UIImage *image = [UIImage imageWithData:data];
-        assetRequest = [PHAssetChangeRequest creationRequestForAssetFromImage:image];
+        assetRequest = [PHAssetChangeRequest creationRequestForAssetFromImageAtFileURL:inputURI];
       }
       placeholder = [assetRequest placeholderForCreatedAsset];
       if (![options[@"album"] isEqualToString:@""]) {
```

**Comment by FelixMo42** [comment]
This bug is still happening, but the patch no longer works. The file has been renamed to `RNCCameraRoll.mm`. Is their any reason this hasn't been changed for everyone?

**Comment by daamsie** [comment]
Would appreciate if this could be reopened. It's annoying to lose the exif data when saving to the camera roll.

**Comment by Arjan-Zuidema** [comment]
I'd be willing to accept a pull request. Maybe @vmia159 you can create a PR based on the patch you created?
