### ISSUE TITLE
I don't get any photos when use groupName for specfic album

### ISSUE THREAD

**Issue by rpss2** [react-native-cameraroll/react-native-cameraroll#41]
I'm use CameraRoll component for get photos by albums, but any photo returned.

**Comment by bartolkaruza** [comment]
Hi there, thanks for reporting. Could you provide a minimal reproduction so we can have a look at this issue?

**Comment by rpss2** [comment]
Basically, I pass album name to groupName prop, e. g. "Recent Photos", and zero photos is returned. But, when I remove this prop, the photos is returned.

**Comment by rpss2** [comment]
Hi, has anyone solved this problem?

**Comment by ruipneves** [comment]
I am also experiencing this issue.
I can only get photos when the `groupType` is `All`. If I try to pass `Album` and get `groupNname: 'Recent Photos'` I get no images at all.

I am using `react-native 0.59.2`

**Comment by albullington** [comment]
I'm experiencing the same, using this code: 

```
getPhotos() {
    const photoOptions = {
      first: 28,
      assetType: "Photos",
      groupName: "Favorites",
      groupTypes: "All"
    };

      CameraRoll.getPhotos( photoOptions ).then( ( results ) => {
         console.log( results.edges );
   }
}
```

The results I'm seeing from results.edges all have a group_name of "All Photos," so it looks like the groupName parameter isn't being used to filter at all. 

I've also tried groupTypes: "Album." I can get images from random albums like "WhatsApp", "Boomerang," and "Instagram" but I can't seem to access the built-in iOS albums like Favorites that all users would consistently have on their devices. I'm not sure how to figure out what group names are on a user's phone to filter by specific group types.

Finally, I've tried simply changing the groupTypes to use Event, SavedPhotos, etc. and they all give really unexpected results. Most return completely empty results, while the rest seem to only return results from my WhatsApp albums.

**Comment by jacobchen** [comment]
I'm experiencing the same issue. I used below code snippet. If I set groupName, it always return an empty list but if I NOT set the groupName it returns a full list of photos.
```
CameraRoll.getPhotos({
            first: 10,
            assetType: "Photos", 
            groupTypes: "All",
            groupName: "Camera Roll"
        }).then(function(result) {
            responseInfoCallback(null, result);
        })
        .catch((error) => {
            console.error(error);
            responseInfoCallback(error);
        });
```

**Comment by lynrose10** [comment]
Same here. It doesn't return expected result

```
_fetchImage = () => {
    CameraRoll.getPhotos({
	first: 10,
	groupTypes: "All",
	assetType: "All",
	groupName: "Screenshots",
    }).then((data) => {
      console.log("data", data);
    });
  }
```
![Screen Shot 2019-07-15 at 9 36 46 PM](https://user-images.githubusercontent.com/29659291/61221076-47785e00-a74a-11e9-8af4-25f6d0c767b5.png)

![Screen Shot 2019-07-15 at 9 45 34 PM](https://user-images.githubusercontent.com/29659291/61221058-3c253280-a74a-11e9-9484-0ea2b5648040.png)

PS: I only have 2 photos on Screenshots album

**Comment by Psiiirus** [comment]
Any solution? i really need the latest taken photos of the phone user

**Comment by Abdelrahman-Nabil** [comment]
+1

**Comment by ZephyrFang** [comment]
+1

**Comment by ZephyrFang** [comment]
I think there is a bug in their code. They don't check the album name parameter (groupName) unless you set the groupType to something not 'all'. 
I change my code from:
 CameraRoll.getPhotos({
        first: 20,
        assetType: 'Photos',
        groupName: group_name,
      })

to 

 CameraRoll.getPhotos({
        first: 20,
        assetType: 'Photos',
        groupName: group_name,
        groupTypes: 'Album',
      })

And it works well now.

I think the bug is in RNCCameraRollManager.m file, line 342:

    if ([groupTypes isEqualToString:@"all"]) {
      PHFetchResult <PHAsset *> *const assetFetchResult = [PHAsset fetchAssetsWithOptions: assetFetchOptions];
      currentCollectionName = @"All Photos";
      [assetFetchResult enumerateObjectsUsingBlock:collectAsset];
    } else {
      PHFetchResult<PHAssetCollection *> *const assetCollectionFetchResult = [PHAssetCollection fetchAssetCollectionsWithType:collectionType subtype:collectionSubtype options:collectionFetchOptions];
      [assetCollectionFetchResult enumerateObjectsUsingBlock:^(PHAssetCollection * _Nonnull assetCollection, NSUInteger collectionIdx, BOOL * _Nonnull stopCollections) {
        // Enumerate assets within the collection
        PHFetchResult<PHAsset *> *const assetsFetchResult = [PHAsset fetchAssetsInAssetCollection:assetCollection options:assetFetchOptions];
        currentCollectionName = [assetCollection localizedTitle];
        [assetsFetchResult enumerateObjectsUsingBlock:collectAsset];
        *stopCollections = stopCollections_;
      }];
    }

**Comment by tommynordli** [comment]
I'm able to get user albums with `groupTypes` set to `Album` or `SavedPhotos`, but I'm not able to get photos from smartAlbums like "Favorites", "Panoramas" or "Selfies".

**Comment by stevejboyer** [comment]
> I'm able to get user albums with `groupTypes` set to `Album` or `SavedPhotos`, but I'm not able to get photos from smartAlbums like "Favorites", "Panoramas" or "Selfies".

Same here. If I find a solution, I'll post it here.

**Comment by George-98** [comment]
I'm struggling with this issue as well! I can't seemed to find a solution to pull out the most recent images taken using the cursor. I found the only solution using the cameraroll component was to request 2000 images and then sort the result via timestamp. However this wan't practical as it lagged out the device.

I ended up just resorting to this npm package which seems to work well so far.
https://www.npmjs.com/package/react-native-imagepicker

**Comment by manithin** [comment]
> > I'm able to get user albums with `groupTypes` set to `Album` or `SavedPhotos`, but I'm not able to get photos from smartAlbums like "Favorites", "Panoramas" or "Selfies".
> 
> Same here. If I find a solution, I'll post it here.

Did you manage to find any solution? same issue here.

**Comment by bobber205** [comment]
I am currently trying lots of different values for `groupName` without ANY value being set for `groupType` and I get nothing.

**Comment by foloinfo** [comment]
I had the same issue but maybe in a slightly different situation.

```
      assetType: 'Photos',
      groupTypes: 'All',
```

This param will return all images but with duplicates.
I checked what was returning as a node in the real device and it turns out group_name was in some weird encoding. I think this string means `All Photos` in Japanese.
I ended up manually filtering nodes using this string. (not with params but js filter)

```
{
  type: 'image',
  group_name: '\M-c\M^A\M^Y\M-c\M^A\M-9\M-c\M^A\M-&\M-c\M^A\M-.\M-e\M^F\M^Y\M-g\M^\\M^_',
```

I'm guessing part of this problem is because I added some localization options to `app.json` but I'm not sure.

```
      "infoPlist": {
        "CFBundleLocalizations" : ["ja"],
        "CFBundleDevelopmentRegion": "ja_JP"
      }
```

Does anybody know what encoding is? or any way to fix it?

**Comment by squalvj** [comment]
i got the same issue, cannot get from favourite in IOS albums

**Comment by tuantai0625** [comment]
Hey guys, I've checked native code in this file
https://github.com/react-native-community/react-native-cameraroll/blob/53e42df323083441b40c532112dc0dcfdf22089b/ios/RNCCameraRollManager.m
The problem is from the way they groupTypes is handled. Bugs is from these codes:
https://github.com/react-native-community/react-native-cameraroll/blob/53e42df323083441b40c532112dc0dcfdf22089b/ios/RNCCameraRollManager.m#L260-L262

https://github.com/react-native-community/react-native-cameraroll/blob/53e42df323083441b40c532112dc0dcfdf22089b/ios/RNCCameraRollManager.m#L371-L384

Im not good in iOS native development but after hours researching, I've found that iOS Photo framework seperate SmartAlbum (Favorites, Recent Photos, etc) from Album (custom album which user create), so if we set groupTypes = 'Album' we cannot get any photos from SmartAlbum because of lines 260 -> 262 codes

**Comment by pribeh** [comment]
Is there any chance one of the maintainers can look at this issue? There's no way seemingly to sort by grouptype it seems.

**Comment by bartolkaruza** [comment]
@r0b0t3d @hsource @pxpeterxu @dokkis Looping you guys in hoping someone has a spare cycle to investigate this issue.

**Comment by pribeh** [comment]
I can confirm @ZephyrFang and @tuantai0625 's points seem to be accurate about groupTypes: Album and SmartAlbum.

**Comment by Maxoos** [comment]
Is there a fix for this? To be able to sort by SmartAlbum is basic functionality on all apps.

**Comment by jbromberg** [comment]
Any solutions? It's pretty common to want to get photos from a user's Favorites album as well as others.

**Comment by ntvinhit** [comment]
The issue is still, the groupName is not work, I still got All photos

**Comment by mykelaballe** [comment]
same here, im not able to get Screenshots album

**Comment by reyanshmishra** [comment]
why no one is taking this seriously? I am pretty sure there must be PR for this? The 19 PR's are pending.

**Comment by nm-antecuic** [comment]
Hi guys.
I managed to make it work after specifying `groupTypes` and `groupName` properties.
My code is like this and works, `RN version-> 0.66.1`, `@react-native-community/cameraroll -> 4.1.2`

CODE:
```
const {edges} = await CameraRoll.getPhotos({
      first: 100 * offset,
      groupTypes: route.params?.selectedAlbum ? 'Album' : 'All',
      groupName: route.params?.selectedAlbum,
      assetType: 'Photos',
    });
```

**Comment by chenweigh** [comment]
same as smartalbum.
who fix it ?

**Comment by Ayzekberk** [comment]
If you want to retrieve an album below parameters are working

first: 10,
groupTypes: "album",
assetType: "photos",
groupName: "YourAlbumName",

**Comment by topervillablanca** [comment]
I think it gets weird on the "Asking permission" part.. when you give access to all photos, the groupName or group_name will automatically use the "All Photos" value

**Comment by locht** [comment]
it deals with uppercase and lowercase letters, 'Album' to 'album', 'Photo' to 'photo'
below parameters are working
first: 10,
groupTypes: "album",
assetType: "photos",
groupName: "YourAlbumName",

**Comment by mingyeom1** [comment]
same

**Comment by bobber205** [comment]
Adding some activity to keep it open

**Comment by idrissakhi** [comment]
would you confirm if this is always the case, otherwise we will be closing the issue

**Comment by efstathiosntonas** [comment]
@idrissakhi if the `groupTypes` is set to `All` when trying to fetch an Album created by the user then if fetches all the photos from the Library. On iOS the `Recents` album is a SmartAlbum thus it won't load any images if we fetch it by `groupTypes:"Album"`.

see this comment: 
* https://github.com/react-native-cameraroll/react-native-cameraroll/issues/41#issuecomment-611970119

**Comment by thaimauit** [comment]
I fixed by add specific groupTypes
Ex: 
first: 10,
groupTypes: "Album", or "SmartAlbum" depend on album
assetType: "Photos",
groupName: "YourAlbumName",

You need to get list album first.

Below code for get list albums:
const allAlbums = await CameraRoll.getAlbums({
      assetType: 'Photos',
      albumType: 'All',
    }) : { tile: string; count: number; type: string };

Every album has a type, use this field for getPhotos

**Comment by Keanu2431** [comment]
Issue still persist, cannot get custom albums when setting group type to 'SmartAlbum'

**Comment by PierreCapo** [comment]
Dear bot, the issue is still present.
